### ISSUE TITLE
Please keep commit history and versioning!

### ISSUE THREAD

**Issue by rfay** [goodhosts/hostsfile#1]
I think it's fine to move this to an org, but a couple of good options:

1. Just change the ownership of the project, and all issues and PRs will go with it.
2. At least keep the commit and version history (by pushing up the git repo)

With either of these (#1 is far better) we can all tell what actually happened and what effect this has on our projects and dependence on this one.

**Comment by luthermonson** [comment]
@rfay I can't for this one, i moved the hostsfile package to a stand alone repo in case any one wants to just use that by itself since the cli only uses this as a library. the cli has the history: https://github.com/goodhosts/cli/commits/master
