### ISSUE TITLE
Larger list of hosts per ip is not working in Windows

### ISSUE THREAD

**Issue by C0mp4ct** [goodhosts/hostsfile#10]
If hosts file has more than 9 hosts per IP, Windows doesn't see the rest of the hosts. [See here](https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-f)

**Comment by luthermonson** [comment]
This is great info, thanks I'll patch it when I find some time.

**Comment by rfay** [comment]
There's loads more info on this in the original issue, https://github.com/lextoumbourou/goodhosts/issues/11 - It seems that multiple lines would help solve the problem.

**Comment by luthermonson** [comment]
@rfay @C0mp4ct this is now supported with the HostsPerLine which can take an int to split, the default behavior in the Clean func will be to pass in the OS specific param, windows is 9 per line and the rest are unlimited.

Additionally, this is merged up to v1.0.5 of the cli, you can use --clean on add/remove or the clean command itself will just scrub what you have in place.

https://github.com/goodhosts/cli/releases/tag/v.1.0.5

I'm closing this issue, if this does not solve the problems please feel free to open a new one with anything that comes from this update.
