### ISSUE TITLE
Q: Why is the position of a host on the line used?

### ISSUE THREAD

**Issue by tomjn** [goodhosts/hostsfile#13]
I'm debugging an issue that's sourced to code introduced in this commit:

https://github.com/goodhosts/hostsfile/commit/57158c4acf4812de4e18728a918eac8fcfe6f628

However, looking at it, I see that a host is being removed based on its position in a list, which does not make sense to me.

Would it not make more sense to generate the list fresh or remove by value? This seems very fragile. Would it not make more sense to de-duplicate any entries then remove by value?

**Comment by luthermonson** [comment]
are you talking about line 285? frankly i dont think that's needed any more as 289 stomps out Lines any way, i think that was from the first writing of that function and i left it in be accident. What is the issue youre seeing? Maybe I can step through the data you have and confirm

**Comment by tomjn** [comment]
Another issue got raised for it at https://github.com/goodhosts/cli/issues/16
