### ISSUE TITLE
Multiple hosts per line added on Windows causes problems

### ISSUE THREAD

**Issue by tomjn** [goodhosts/hostsfile#18]
I had users reporting that sites they were using would not load with 16 host entries on a line.

Further research indicates that Windows has an upper limit of 9 alias' per entry

#17 attempts to fix this

**Comment by tomjn** [comment]
@luthermonson do you have any idea why this is happening? I can see that there is code that attempts to implement this, but it is non-functional. I have users opening notepad.exe as administrators to fix this issue manually because goodhosts adds too many hosts on the same file when using the `vagrant-goodhost` plugin

**Comment by gbraad** [comment]
Will try to propose a fix. Seems this issue has been open for quite some time.

A post-process might be a possible workaround? You can try Windows Host File Optimizer or a powershell script for this.

**Comment by tomjn** [comment]
@gbraad see https://github.com/goodhosts/hostsfile/pull/17#discussion_r687281993 I think that's what needs to happen
