### ISSUE TITLE
Deputize maintainers/reviewers/testers

### ISSUE THREAD

**Issue by tomjn** [goodhosts/hostsfile#23]
@luthermonson isn't always around yet this project is a critical dependency of many other projects.

Various non-admin/owner level roles should be delegated out to volunteers so that @luthermonson isn't needed for mundane low level tasks such as code review or testing

**Comment by tomjn** [comment]
@luthermonson *poke*

**Comment by luthermonson** [comment]
yup, never meant to be a fiefdom and sorry about being an absentee maintainer. huge thanks for pushing this issue and ive added @mte90 and @tomjn as owners of the org
