### ISSUE TITLE
HostsPerLine is destructive

### ISSUE THREAD

**Issue by tomjn** [goodhosts/hostsfile#40]
The `HostsPerLine` function is destructive, and does a number of unexpected things:

 - it de-dupes which is the responsibility of a different function
 - it's stripping out comments

I believe this is related to https://github.com/goodhosts/vagrant/issues/51

**Comment by jd4u** [comment]
The issue seems to be in goodhosts/cli project. With or without "--clean" flag, cli is performing clean process. See [Issue Comment](https://github.com/goodhosts/vagrant/issues/51#issuecomment-1336280251) 

The cli project seems to be handling bool value incorrectly. Explicitly setting default bool value may help.

**Comment by tomjn** [comment]
Note that I cannot reproduce this on MacOS, this is very likely Windows related.

We need to confirm what the command is doing to the hosts file in addition to stripping out comments to eliminate options, my current theory is that this has nothing to do with the clean parameters, but due to the attempt to workaround a Windows bug where more than 8 hosts on a line breaks the hosts file.

We can confirm this if we had examples that can be used to see if it's sorting the hosts file, merging lines that were previously separate, etc

**Comment by tomjn** [comment]
@luthermonson is it possible that this is all because of the Ip de-duplication at the top of that function?

```go
func (h *Hosts) HostsPerLine(count int) {
	// restacks everything into 1 ip again so we can do the split, do this even if count is -1 so it can reset the slice
	h.RemoveDuplicateIps()
```

**Comment by tomjn** [comment]
@jd4u is reporting that comments were stripped from their hosts file on use regardless of wether the clean parameter was specified or not. They're a WIndows user so `HostsPerLine` would be running to cap the lines at 8 hosts

**Comment by jd4u** [comment]
Yes @tomjn, you may be pointing right place.

- RemoveDuplicateIPs is called within Clean along with HostPerLine
- Clean function does Sort before making HostPerLine.
- RemoveDuplicateIPs is called from HostPerLine too.
- So even someone just calls HostPerLine, RemoveDuplicateIPs are called.

**Comment by jd4u** [comment]
Just for note, 
- in VVV config, only 6 active sites present. 
- And none of the IP had or have more than 4 hostnames in machine hosts file.

**Comment by rfay** [comment]
Comments are stripped regardless of the cli; you can 

https://github.com/goodhosts/hostsfile/issues/40

This is easy to demonstrate with https://github.com/rfay/goodhostsbug

**Comment by rfay** [comment]
One improvement here would be to respect "important" standard lines like "localhost". A longer-term improvement would be to add separate lines for goodhosts-managed lines (probably marked with a comment before and after).

**Comment by rfay** [comment]
I've seen some good maintenance going on in this area lately, thanks! Has this one been addressed yet?

**Comment by luthermonson** [comment]
ya all that stuff got refactored to index the lookup hashmaps better. i bet your example repo works against latest main, give it a check and report back findings and ill fix if still broke

**Comment by rfay** [comment]
No, it still makes a pretty big mess. Comments are mostly destroyed and misplaced. I updated https://github.com/rfay/goodhostsbug and its readme to show more how to demonstrate it. 

Bottom line is that 
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

gets transformed to

```
127.0.0.1 localhost xxx.ddev.site
255.255.255.255 broadcasthost
::1 localhost
  # Host Database
```

**Comment by luthermonson** [comment]
im sorry i wasted your time... I forgot I hadn't released the changes here https://github.com/goodhosts/hostsfile/pull/46

please try with v0.1.4 as with a test off latest main i got the following...

```
func Test_rfay(t *testing.T) {
	hosts := newMacOSXDefault()
	assert.Nil(t, hosts.Add("127.0.0.1", "xxx.ddev.site"))
	hosts.HostsPerLine(8)
	fmt.Println(hosts.String())
}
```

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost xxx.ddev.site
255.255.255.255 broadcasthost
::1 localhost
```

**Comment by rfay** [comment]
Yay, it's working great! This issue can be closed (at least about the comments), thanks so much!

**Comment by luthermonson** [comment]
My pleasure! Glad it's working

**Comment by rfay** [comment]
Thanks so much for your maintenance of this! Reopened
* https://github.com/ddev/ddev/pull/4805
